language: python
python: "2.7"
install:
  - "pip install ."
  - "pip install pytest"
  - "pip install coverage"
  - "pip install coveralls"
script: 'coverage run --source "." --omit "setup.py,tests/speed_tests.py" -m py.test'
after_success: coveralls
